services:
  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
